=== BlackPandazz247/xml/SquadraCalcio/squadra.dtd
<!ELEMENT squadra (presidente, allenatore, giocatore+)>
<!ELEMENT presidente (#PCDATA)>
<!ELEMENT allenatore (#PCDATA)>
<!ELEMENT giocatore (nome, ruolo+)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT ruolo (#PCDATA)>
<!ATTLIST squadra
    nome CDATA #REQUIRED
    serie (A|B|C1|C2|C3) #REQUIRED
>
<!ATTLIST giocatore titolare (si|no) #REQUIRED>

=== BlackPandazz247/xml/SquadraCalcio/squadra.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE squadra SYSTEM "squadra.dtd">
<squadra nome="Juminter" serie="C1">
    <presidente>Mario Rossi</presidente>
    <allenatore>Giuseppe Bianchi</allenatore>
    <giocatore titolare="si">
        <nome>Leonardo Da Vinci</nome>
        <ruolo>terzino</ruolo>
    </giocatore>
    <giocatore titolare="no">
        <nome>Cristoforo Colombo</nome>
        <ruolo>attacante</ruolo>
        <ruolo>mezzala</ruolo>
    </giocatore>
    <giocatore titolare="si">
        <nome>Giulio Cesare</nome>
        <ruolo>difensore</ruolo>
    </giocatore>
</squadra>
